apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes-deploy
    spec:
      containers:
        - name: kuber-test-pod
          image: test-kuber-deployment:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: kubernetes-deploy